# Generated by Django 4.2 on 2023-05-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="useremail",
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=128),
        ),
    ]
