# Generated by Django 4.2.1 on 2023-05-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafemapapp', '0002_studycafes_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studycafes',
        ),
    ]
