# Generated by Django 4.2.1 on 2023-05-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafemapapp', '0004_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Studycafes',
        ),
    ]
