# Generated by Django 4.2.1 on 2023-05-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafemapapp', '0006_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
