# Generated by Django 4.2.1 on 2023-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sca_name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='스터디카페'),
        ),
    ]
