# Generated by Django 4.2 on 2023-05-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_user_password_alter_user_useremail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="제목")),
                ("contents", models.TextField(verbose_name="내용")),
                (
                    "registered_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록 시간"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
                "db_table": "community_board",
            },
        ),
    ]
