# Generated by Django 4.2 on 2023-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="body",),
        migrations.RemoveField(model_name="comment", name="post",),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.CharField(default=1, max_length=100, verbose_name="내용"),
            preserve_default=False,
        ),
    ]
